import { Property } from "./types";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description: "Beautiful modern apartment in the heart of downtown with stunning city views.",
    price: 450000,
    type: "sale",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Balcony", "Gym", "Parking", "Pool"],
    isFeatured: true,
  },
  {
    id: "2",
    title: "Luxury Family Home",
    description: "Spacious family home with large backyard and modern amenities.",
    price: 850000,
    type: "sale",
    propertyType: "house",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    address: "456 Oak Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90210",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Garden", "Garage", "Fireplace", "Renovated"],
    isFeatured: true,
  },
  {
    id: "3",
    title: "Cozy Studio Apartment",
    description: "Compact and efficient studio apartment perfect for singles or couples.",
    price: 1200,
    type: "rent",
    propertyType: "apartment",
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    address: "789 Pine St",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Pet Friendly", "Laundry", "High-Speed Internet"],
  },
  {
    id: "4",
    title: "Waterfront Condo",
    description: "Stunning waterfront condo with panoramic ocean views and luxury finishes.",
    price: 1200000,
    type: "sale",
    propertyType: "condo",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    address: "101 Beach Blvd",
    city: "Miami",
    state: "FL",
    zipCode: "33139",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Ocean View", "Balcony", "Concierge", "Pool", "Gym"],
    isFeatured: true,
  },
  {
    id: "5",
    title: "Downtown Loft",
    description: "Industrial-style loft in the trendy downtown district with high ceilings.",
    price: 2200,
    type: "rent",
    propertyType: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    address: "222 Loft St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["High Ceilings", "Exposed Brick", "Hardwood Floors", "Parking"],
  },
  {
    id: "6",
    title: "Suburban Townhouse",
    description: "Well-maintained townhouse in a quiet suburban neighborhood with good schools.",
    price: 320000,
    type: "sale",
    propertyType: "townhouse",
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    address: "333 Family Ln",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Backyard", "Garage", "Updated Kitchen", "Quiet Neighborhood"],
  },
  {
    id: "7",
    title: "Luxury Penthouse",
    description: "Exclusive penthouse with private terrace and panoramic city views.",
    price: 3500000,
    type: "sale",
    propertyType: "apartment",
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    address: "444 Elite Ave",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Private Terrace", "Concierge", "Gym", "Pool", "Wine Cellar"],
    isFeatured: true,
  },
  {
    id: "8",
    title: "Charming Cottage",
    description: "Quaint cottage with beautiful garden and historic character.",
    price: 1800,
    type: "rent",
    propertyType: "house",
    bedrooms: 2,
    bathrooms: 1,
    area: 800,
    address: "555 Garden Rd",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    image: "https://images.unsplash.com/photo-1575517111839-3a3843ee7f5d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    features: ["Garden", "Historic", "Patio", "Natural Light"],
  },
];